Apartment/Models/ApartmentDetailsViewModel.cs
namespace Apartment.Models
{
    public class ApartmentDetailsViewModel
    {
        public Apartment.Data.Models.Apartment Apartment { get; set; }
    }
}

Apartment/Models/HomeViewModel.cs
using Microsoft.AspNetCore.Mvc;

namespace Apartment.Models
{
    public class HomeViewModel
    {
        public List<Apartment.Data.Models.Apartment> Apartments { get; set; } = new List<Data.Models.Apartment>();
        public string Name { get; set; }
        [FromQuery(Name = "take")]
        public int Take { get; set; } = 10;
        [FromQuery(Name = "skip")]
        public int Skip { get; set; } = 0;
    }
}

Apartment/Controllers/ApartmentDetailsController.cs
using Apartment.Models;
using Apartment.Repositories;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Apartment.Controllers
{
    public class ApartmentDetailsController : Controller
    {
        private readonly IApartmentRepository _repository;

        public ApartmentDetailsController(IApartmentRepository repository)
        {
            _repository = repository;
        }

        public async Task<ActionResult> Details(int id)
        {
            var result = await _repository.GetByIdAsync(id);
            var viewModel = new ApartmentDetailsViewModel { Apartment = result };
            return View(viewModel);
        }
    }
}

Apartment/Controllers/HomeController.cs
using Apartment.Models;
using Apartment.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace Apartment.Controllers
{
    public class HomeController : Controller
    {
        private readonly IApartmentRepository _repository;

        public HomeController(IApartmentRepository repository)
        {
            _repository = repository;
        }

        [HttpGet]
        public async Task<IActionResult> Index([FromQuery]string? name, int take = 10, int skip = 0)
        {
            if (TempDataExist())
            {
                var viewModel = CreateViewModelFromTempData();
                viewModel.Apartments = await _repository.GetPaginatedAsync(viewModel.Name, viewModel.Take, viewModel.Skip);
                return View(viewModel);
            }
            else
            {
                var result = await _repository.GetPaginatedAsync(name, take, skip);
                var viewModel = new HomeViewModel { Apartments = result, Skip = skip, Take = take };
                return View(viewModel);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Index(HomeViewModel viewModel)
        {
            TempData["name"] = viewModel.Name;
            TempData["take"] = viewModel.Take;
            TempData["skip"] = viewModel.Skip;
            return RedirectToAction("Index");
        }
         
        private HomeViewModel CreateViewModelFromTempData()
        {
            return new HomeViewModel
            {
                Skip = (int)TempData["skip"],
                Take = (int)TempData["take"],
                Name = TempData["name"]?.ToString()
            };
        }

        private bool TempDataExist()
        {
            return TempData.ContainsKey("name") && TempData.ContainsKey("take") && TempData.ContainsKey("skip");
        }
    }
}

Apartment/Views/ApartmentDetails/Details.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model ApartmentDetailsViewModel

<div class="card" style="width: 18rem;">
    <img class="card-img-top" src="~/images/bekavac.jpg" alt="Card image cap">
    <div class="card-body">
        <h5 class="card-title">@Model.Apartment.Name</h5>
        <h6 class="card-subtitle mb-2 text-muted">@Model.Apartment.OwnerName</h6>
        <p class="card-text">
            <span><strong>NO. Bathrooms:</strong> @Model.Apartment.Bathrooms </span> <br/>
            <span><strong>NO. Bedrooms:</strong> @Model.Apartment.Bedrooms</span>
        </p>
    </div>
</div>

Apartment/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model HomeViewModel


<form asp-controller="Home" asp-action="Index" method="post">
    <div class="input-group input-group-sm mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text" id="inputGroup-sizing-sm">Search by name</span>
        </div>
        @Html.TextBoxFor(model => model.Name, new { placeholder=Html.DisplayNameFor(model => model.Name), @class="form-control"})
        <button type="submit" class="btn btn-primary">Search</button>
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">OwnerName</th>
            <th scope="col">Bathrooms</th>
            <th scope="col">Bedrooms</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            @foreach (var item in Model.Apartments)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.OwnerName</td>
                    <td>@item.Bathrooms</td>
                    <td>@item.Bedrooms</td>
                    <td>
                        <a class="btn btn-primary" href="@Url.Action("Details", "ApartmentDetails", new { id = item.Id })" role="button">Open apartment details</a>
                    </td>
                </tr>
            }
        }

    </tbody>
</table>

Apartment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Apartment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Apartment.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Apartment</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Apartment - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>